const quotes = [
    { text: "Beware that, when fighting monsters, you yourself do not become a monster... for when you gaze long into the abyss. The abyss gazes also into you.", author: "Friedrich W. Nietzsche" },
    { text: "And those who were seen dancing were thought to be insane by those who could not hear the music.", author: "Friedrich W. Nietzsche" },
    { text: "Nobody ever figures out what life is all about, and it doesn't matter. Explore the world. Nearly everything is fascinating if you go into it deeply enough.", author: "Richard P. Feynman" },
    { text: "Physics is like sex: sure, it may give some practical results, but that's not why we do it.", author: "Richard P. Feynman" },
    { text: "What does a hot plate look like? A cold plate." },
    { text: "The henderson-hasselbalch equation is nothing special; it's just rearranging the Ka expression and taking the negative log. However, since two biologists were able to figure it out, we named it after them." },
    { text: "The world is a construct of our sensations, perceptions, memories. It is convenient to regard it as existing objectively on its own. But it certainly does not become manifest by its mere existence.", author: "Erwin Schrödinger" },
    { text: "If you cannot—in the long run—tell everyone what you have been doing, your doing has been worthless.", author: "Erwin Schrödinger" },
    { text: "A great advantage of X-ray analysis as a method of chemical structure analysis is its power to show some totally unexpected and surprising structure with, at the same time, complete certainty. Dorothy Crowfoot Hodgkin" },
    { text: "X-rays will prove to be a hoax.", author: "Baron William Thomson Kelvin" },
    { text: "I don't like it, and I'm sorry I ever had anything to do with it. (About the probability interpretation of quantum mechanics.)", author: " Erwin Schrödinger" },
    { text: "There are no facts, only interpretations.", author: "Friedrich Nietzsche" },
    { text: "Ludwig Boltzmann, who spent much of his life studying statistical mechanics, died in 1906, by his own hand. Paul Ehrenfest, carrying on the work, died similarly in 1933. Now it is our turn to study statistical mechanics. Perhaps it will be wise to approach the subject cautiously.", author: "David Goodstein" },
    { text: "No man has the right to be an amateur in the matter of physical training. It is a shame for a man to grow old without seeing the beauty and strength of which his body is capable.", author: "Socrates" },
    { text: "Not only is the Universe stranger than we think, it is stranger than we can think.", author: "Werner Heisenberg" },
    { text: "There are things that are so serious that you can only joke about them.", author: "Werner Heisenberg" },
    { text: "As man seeks justice in equality, so society seeks order in anarchy.", author: "Pierre-Joseph Proudhon" },
    { text: "Practice Is the Criterion of Truth.", author: "Karl Marx" },
    { text: "If you took the most ardent revolutionary, vested him in absolute power, within a year he would be worse than the Tsar himself.", author: "Mikhail Bakunin" },
    { text: "The freedom of all is essential to my freedom.", author: "Mikhail Bakunin" },
    { text: "One glance at a book, and you hear the voice of another person, perhaps someone dead for 1,000 years. To read is to voyage through time.", author: "Carl Sagan" },
    { text: "The problem is not people being uneducated. The problem is that people are educated just enough to believe what they have been taught, but not educated enough to question what they have been taught.", author: "Richard Feynman" },
    { text: "When a man loves cats, I am his friend and comrade, without further introduction.", author: "Mark Twain" },
    { text: "If facts hurt your feelings you need new feelings, not new facts.", author: "Ricky Gervais" },
    { text: "It is our choice of good or evil that determines our character, not our opinion about good or evil.", author: "Aristotle" },
    { text: "Start where you are, use what you have, do what you can.", author: "Arthur Ashe" },
    { text: "I have no special talent. I am only passionately curious.", author: "Albert Einstein" },
    { text: "My solitude doesn't depend on the presence or absence of people; on the contrary, I hate who steals my solitude without, in exchange, offering me true company.", author: "Friedrich Nietzsche" },
    { text: "Every man is guilty of all the good he did not do.", author: "Voltaire" },
    { text: "If you are lonely when you're alone, you are in bad company.", author: "Jean-Paul Sartre" },
    { text: "Laugh and the world laughs with you. Weep and you weep alone.", author: "Dae-su Oh (Oldboy)" },
    { text: "I don’t mind being shot, man. But I don’t dig being told about it.", author: "Bob Dylan" },
    { text: "They say that people shrivel up because of their imaginations. So don’t imagine anything. You’ll become brave as hell.", author: "Woo-jin Lee (Oldboy)" },
    { text:  "The meaning of my existence is that life has addressed a question to me. Or, conversely, I myself am a question which is addressed to the world, and I must communicate my answer, for otherwise I am dependent upon the world’s answer.", author: "Carl Jung" },
    { text: "Science is organized knowledge. Wisdom is organized life.", author: "Immanuel Kant" },
    { text: "The science of today is the technology of tomorrow.", author: "Edward Teller" },
    { text: "Chemistry can be a good and bad thing. Chemistry is good when you make love with it. Chemistry is bad when you make crack with it.", author: "Adam Sandler" },
    { text: "Science is not only a disciple of reason but also one of romance and passion.", author: "Stephen Hawking" },
    { text: "Chemistry is the study of matter, but I prefer to see it as the study of change.", author: "Walter White" },
    { text: "Science knows no country, because knowledge belongs to humanity, and is the torch which illuminates the world.", author: "Louis Pasteur" },
    { text: "The aim of art is to represent not the outward appearance of things, but their inward significance.", author: "Aristotle" },
    { text: "Art is the lie that enables us to realize the truth.", author: "Pablo Picasso" },
    { text: "Philosophy is to the mind what the eyes are to the body.", author: "Immanuel Kant" },
    { text: "What spirit is so empty and blind, that it cannot recognize the fact that the foot is more noble than the shoe, and skin more beautiful than the garment with which it is clothed?", author: "Michelangelo" },
    { text: "Every block of stone has a statue inside it, and it is the task of the sculptor to discover it.", author: "Michelangelo" },
    { text: "If you don't fail at least 90 percent of the time, you're not aiming high enough.", author: "Alan Kay" },
    { text: "Art is not what you see but what you make others see.", author: "Edgar Degas" },
    { text: "Art is a lie that makes us realize the truth.", author: "Pablo Picasso" },
    { text: "Color is my day-long obsession, joy, and torment.", author: "Claude Monet" },
    { text: "To see we must forget the name of the thing we are looking at.", author: "Claude Monet" },
    { text: "Eureka!", author: "Archimedes" },
    { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
    { text: "In the middle of every difficulty lies oportunity.", author: "Albert Einstein" },
    { text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
    { text: "The Earth is not given to us by our parents, it is loaned to us by our children.", author: "Kenyan proverb" },
    { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
    { text: "The universe is under no obligation to make sense to you.", author: "Neil deGrasse Tyson" },
    { text: "Science knows no country because knowledge belongs to humanity, and is the torch which illuminates the world.", author: "Louis Pasteur" },
    { text: "Science is the poetry of reality.", author: "Richard Dawkins" },
    { text: "Science, my lad, is made up of mistakes, but they are mistakes which it is useful to make because they lead little by little to the truth.", author: "Jules Verne" },
    { text: "Science is a way of thinking much more than it is a body of knowledge.", author: "Carl Sagan" },
    { text: "In science, there are no shortcuts to truth.", author: "Carl Sagan" },
    { text: "Science and art sometimes can touch one another, like two pieces of the jigsaw puzzle which is our human life.", author: "Salvador Dali" },
    { text: "The most exciting phrase to hear in science, the one that heralds new discoveries, is not 'Eureka!' but 'That's funny...", author: "Isaac Asimov" },
    { text: "Science is not only compatible with spirituality; it is a profound source of spirituality.", author: "Carl Sagan" },
    { text: "The universe is full of magical things, patiently waiting for our wits to grow sharper.", author: "Eden Phillpotts" },
    { text: "We are just an advanced breed of monkeys on a minor planet of a very average star. But we can understand the Universe. That makes us something very special.", author: "Stephen Hawking" },
    { text: "The good thing about science is that it's true whether you believe in it or not.", author: "Neil deGrasse Tyson" },
    { text: "Scientific discovery and scientific knowledge have been achieved only by those who have gone in pursuit of it without any practical purpose whatsoever in view. Max Planck" },
    { text: "Science is not only a disciple of reason but, also, one of romance and passion.", author: "Stephen Hawking" },
    { text: "There is only one corner of the universe you can be certain of improving, and that's your own self.", author: "Aldous Huxley" },
    { text: " After silence, that which comes nearest to expressing the inexpressible is music.", author: "Aldous Huxley" },
    { text: "That men do not learn very much from the lessons of history is the most important of all the lessons of history.", author: "Aldous Huxley" },
    { text: "Facts do not cease to exist because they are ignored.", author: "Aldous Huxley" },
    { text: "You shall know the truth, and the truth shall make you mad.", author: "Aldous Huxley" },
    { text: "Hell isn't merely paved with good intentions; it's walled and roofed with them. Yes, and furnished too.", author: "Aldous Huxley" },
    { text: "You are never really playing an opponent. You are playing yourself, your own highest standards, and when you reach your limits, that is real joy.", author: "Arthur Ashe" },
    { text: "Winning isn't everything, but wanting to win is.", author: "Vince Lombardi" },
    { text: "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice, and most of all, love of what you are doing or learning to do.", author: "Pele" },
    { text: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.", author: "Vince Lombardi" },
    { text: "I've missed more than 9000 shots in my career. I've lost almost 300 games. Twenty-six times I've been trusted to take the game-winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.", author: "Michael Jordan" },
    { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
    { text: "Is not the will to win that matters. Everyone has that. It's the will to prepare to win that matters.", author: "Paul 'Bear' Bryant" },
    { text: "It's a moment that I'm after, a feeling of something special. I rarely end up where I wanted to go, but almost always end up somewhere I need to be.", author: "Dirk Nowitzki" },
    { text: "Our victory won't be by accident", author: "Marcelo D2" },
    { text: "The most incomprehensible thing about the world is that it is comprehensible", author: "Albert Einstein" },
    { text: "All the following have matching behaviours when arriving to a new place: Babies, junkies and rural residents   Something like whoaaaa", author: "João Carvalho" },
    { text: "When you hear hoofs, 99% of the the time is a horse, 1% of the time is a zebra, and it never is an unicorn", author: "João Carvalho" },
    { text: "Extraordinary claims require extraordinary evidence", author: "Carl Sagan" },
    { text: "I believe in intuitions and inspirations. I sometimes fell that i am right. I do not know if I am.", author: "Albert Einstein" },
    { text: "It would be better if you begin to teach others only after you yourself havel learned something.", author: "Albert Einstein" },
    { text: "Science will stagnate if it is made to serve pratical goals", author: "Albert Einstein" },
    { text: "After a certain high level of technical skill is achieved, science and art tend to coalesce in esthetics, plasticity, and form. The greatest scientists are always artists as well.", author: " Albert Einstein" },
];

function displayRandomQuote() {
    const random_quote = document.getElementById('random_quote');
    const currentTime = new Date().getTime();
    const lastUpdateTime = localStorage.getItem('lastUpdateTime');
    const storedQuote = localStorage.getItem('dailyQuote');
    // Refresh quote every 3 hours.
    if (storedQuote && lastUpdateTime && currentTime - lastUpdateTime < 10800000) {
        random_quote.innerHTML = storedQuote;
    } else {
        const randomIndex = Math.floor(Math.random() * quotes.length);
        const quote = quotes[randomIndex];
        const formattedQuote = `<h3>${quote.text}</h3><h2>${quote.author}</h2>`;
        localStorage.setItem('dailyQuote', formattedQuote);
        localStorage.setItem('lastUpdateTime', currentTime.toString());
        random_quote.innerHTML = formattedQuote;
    }
}
