local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local c = ls.choice_node
local f = ls.function_node
local rep = require("luasnip.extras").rep

local snippets = {
  s({ trig = "dumime", dscr = "Mime type options" }, {
    c(1, {
      t("text/plain;"),
      t("text/markdown;"),
      t("text/css;"),
      t("text/html;"),
      t("image/png;"),
      t("image/jpeg;"),
      t("image/svg+xml;"),
      t("video/mp4;"),
      t("video/x-matroska;"),
      t("audio/mpeg;"),
      t("audio/wav;"),
      t("audio/ogg;"),
      t("applications/pdf;"),
      t("applications/vnd.ms-excel;"),
    }),
  }),

  s({ trig = "ducats", dscr = "Desktop categories" }, {
    c(1, {
      t("AudioVideo;"),
      t("Development;"),
      t("Education;"),
      t("Game;"),
      t("Graphics;"),
      t("Network;"),
      t("Office;"),
      t("Settings;"),
      t("System;"),
      t("Utility;"),
      t("Audio;"),
      t("Video;"),
      t("Player;"),
      t("Recorder;"),
      t("Camera;"),
      t("Programming;"),
      t("Science;"),
      t("Sports;"),
      t("TextEditor;"),
      t("Calculator;"),
    }),
  }),

  s({ trig = "ducatsextras", dscr = "Desktop extra categories" }, {
    c(1, {
      t("Building;"),
      t("Debugger;"),
      t("IDE;"),
      t("GUIDesigner;"),
      t("Profiling;"),
      t("RevisionControl;"),
      t("Translation;"),
      t("Calendar;"),
      t("ContactManagement;"),
      t("Database;"),
      t("Dictionary;"),
      t("Chart;"),
      t("Email;"),
      t("Finance;"),
      t("FlowChart;"),
      t("PDA;"),
      t("ProjectManagement;"),
      t("Presentation;"),
      t("Spreadsheet;"),
      t("WordProcessor;"),
      t("2DGraphics;"),
      t("VectorGraphics;"),
      t("RasterGraphics;"),
      t("3DGraphics;"),
      t("Scanning;"),
      t("OCR;"),
      t("Photography;"),
      t("Publishing;"),
      t("Viewer;"),
      t("TextTools;"),
      t("DesktopSettings;"),
      t("HardwareSettings;"),
      t("Printing;"),
      t("PackageManager;"),
      t("Dialup;"),
      t("InstantMessaging;"),
      t("Chat;"),
      t("IRCClient;"),
      t("Feed;"),
      t("FileTransfer;"),
      t("HamRadio;"),
      t("News;"),
      t("P2P;"),
      t("RemoteAccess;"),
      t("Telephony;"),
      t("TelephonyTools;"),
      t("VideoConference;"),
      t("WebBrowser;"),
      t("WebDevelopment;"),
      t("Midi;"),
      t("Mixer;"),
      t("Sequencer;"),
      t("Tuner;"),
      t("TV;"),
      t("AudioVideoEditing;"),
      t("Player;"),
      t("Recorder;"),
      t("DiscBurning;"),
      t("Art;"),
      t("Construction;"),
      t("Music;"),
      t("Astronomy;"),
      t("Biology;"),
      t("Chemistry;"),
      t("ComputerScience;"),
      t("DataVisualization;"),
      t("Eletricity;"),
      t("ImageProcessing;"),
      t("Math;"),
      t("Physics;"),
      t("Robotics;"),
      t("Archiving;"),
      t("Eletronics;"),
      t("Emulator;"),
      t("FileTools;"),
      t("FileManager;"),
      t("TerminalEmulator;"),
      t("Filesystem;"),
      t("Monitor;"),
      t("ConsoleOnly;"),
      t("java;"),
      t("Qt;"),
      t("GTK;"),
      t("GNOME;"),
      t("KDE;"),
      t("Core;"),
      t("Documentation;"),
      t("TextEditor;"),
      t("Clock;"),
      t("Calculator;"),
      t("Acessibility;"),
      t("Security;"),
    }),
  })
}

ls.add_snippets("desktop", snippets)
